namespace EQBuddy.Core;

internal static class SkyQuestDefaults
{
    public static readonly SkyQuestChecklistItem[] Items =
    [
        SkyLine("sky-007|Bard|Cilin Spellsinger|Amulet of the Fae|Amulet of Woven Hair|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-008|Bard|Cilin Spellsinger|Amulet of the Fae|Wind Rune Caza|Trash mobs"),
        SkyLine("sky-009|Bard|Cilin Spellsinger|Denon's Horn of Disaster|Efreeti War Horn|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-010|Bard|Cilin Spellsinger|Denon's Horn of Disaster|Glowing Diamond|Isle 7: Sister of the Spire"),
        SkyLine("sky-011|Bard|Cilin Spellsinger|Denon's Horn of Disaster|Wind Rune Fana|Trash mobs"),
        SkyLine("sky-001|Bard|Cilin Spellsinger|Ervaj's Flute of Flight|Crude Wooden Flute|Isle 5: The Spiroc Lord"),
        SkyLine("sky-002|Bard|Cilin Spellsinger|Ervaj's Flute of Flight|Wind Rune Azia|Trash mobs"),
        SkyLine("sky-012|Bard|Cilin Spellsinger|Harmonic Spear|Efreeti War Spear|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-013|Bard|Cilin Spellsinger|Harmonic Spear|Nebulous Diamond|Isle 8: Eye of Veeshan"),
        SkyLine("sky-014|Bard|Cilin Spellsinger|Harmonic Spear|Wind Rune Heda|Trash mobs"),
        SkyLine("sky-003|Bard|Cilin Spellsinger|Mantle of the Songweaver|Light Woolen Mantle|Isle 4: Keeper of Souls"),
        SkyLine("sky-004|Bard|Cilin Spellsinger|Mantle of the Songweaver|Wind Rune Kala|Trash mobs"),
        SkyLine("sky-005|Bard|Cilin Spellsinger|Mask of Song|Light Woolen Mask|Isle 3: Gorgalosk"),
        SkyLine("sky-006|Bard|Cilin Spellsinger|Mask of Song|Wind Rune Meda|Trash mobs"),
        SkyLine("sky-015|Beastlord|Animist Kratho|Azarack Skin Wristwraps|Azarack Skin|Isle 2: Protector of Sky"),
        SkyLine("sky-016|Beastlord|Animist Kratho|Azarack Skin Wristwraps|Wind Rune Heda|Trash mobs"),
        SkyLine("sky-017|Beastlord|Animist Kratho|Diaphonous Waistband|Silken Wrap|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-018|Beastlord|Animist Kratho|Diaphonous Waistband|Wind Rune Geza|Trash mobs"),
        SkyLine("sky-019|Beastlord|Animist Kratho|Griffin-Hide Armguards|Leather Cord|Isle 3: Gorgalosk"),
        SkyLine("sky-020|Beastlord|Animist Kratho|Griffin-Hide Armguards|Wind Rune Kala|Trash mobs"),
        SkyLine("sky-021|Beastlord|Animist Kratho|Spiroc Beak Earcuff|Spiroc Elder's Totem|Isle 5: The Spiroc Lord"),
        SkyLine("sky-022|Beastlord|Animist Kratho|Spiroc Beak Earcuff|Wind Rune Beza|Trash mobs"),
        SkyLine("sky-023|Beastlord|Animist Kratho|Windhowl/Spirit Render|Brass Knuckles|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-024|Beastlord|Animist Kratho|Windhowl/Spirit Render|Mithril Bands|Isle 8: Eye of Veeshan"),
        SkyLine("sky-025|Beastlord|Animist Kratho|Windhowl/Spirit Render|Sphinx Claw|Isle 7: Sister of the Spire"),
        SkyLine("sky-026|Beastlord|Animist Kratho|Windhowl/Spirit Render|Wind Rune Izah|Trash mobs"),
        SkyLine("sky-027|Berserker|Stragen The Hewer|Blood-Drawn Runes|Azarack Blood|Isle 2: Protector of Sky"),
        SkyLine("sky-028|Berserker|Stragen The Hewer|Blood-Drawn Runes|Wind Rune Lena|Trash mobs"),
        SkyLine("sky-029|Berserker|Stragen The Hewer|Cudgel of the Fool|Efreeti Great Staff|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-030|Berserker|Stragen The Hewer|Cudgel of the Fool|Jester's Mask|Isle 4: Keeper of Souls"),
        SkyLine("sky-031|Berserker|Stragen The Hewer|Cudgel of the Fool|Wind Rune Dena|Trash mobs"),
        SkyLine("sky-032|Berserker|Stragen The Hewer|Molten Coil|Pulsating Ruby|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-033|Berserker|Stragen The Hewer|Molten Coil|Wind Rune Ena|Trash mobs"),
        SkyLine("sky-034|Berserker|Stragen The Hewer|Sash of Ferocity|High Quality Raiment|Isle 5: The Spiroc Lord"),
        SkyLine("sky-035|Berserker|Stragen The Hewer|Sash of Ferocity|Wind Rune Ozah|Trash mobs"),
        SkyLine("sky-036|Berserker|Stragen The Hewer|Shroud of the Sky|Feathered Cape|Isle 3: Gorgalosk"),
        SkyLine("sky-037|Berserker|Stragen The Hewer|Shroud of the Sky|Wind Rune Azia|Trash mobs"),
        SkyLine("sky-038|Berserker|Stragen The Hewer|Skycleaver|Efreeti Standard|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-039|Berserker|Stragen The Hewer|Skycleaver|Djinni War Blade|Isle 7: Sister of the Spire"),
        SkyLine("sky-040|Berserker|Stragen The Hewer|Skycleaver|Wind Rune Jaka|Trash mobs"),
        SkyLine("sky-041|Cleric|Josin Faithbringer|Aegis of the Wind|Small Shield|Isle 4: Keeper of Souls"),
        SkyLine("sky-042|Cleric|Josin Faithbringer|Aegis of the Wind|Wind Rune Meda|Trash mobs"),
        SkyLine("sky-047|Cleric|Josin Faithbringer|Baton of the Sky|Efreeti Standard|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-048|Cleric|Josin Faithbringer|Baton of the Sky|Mithril Bands|Isle 8: Eye of Veeshan"),
        SkyLine("sky-049|Cleric|Josin Faithbringer|Baton of the Sky|Wind Rune Ena|Trash mobs"),
        SkyLine("sky-050|Cleric|Josin Faithbringer|Necklace of Resolution|Silvered Spiroc Necklace|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-051|Cleric|Josin Faithbringer|Necklace of Resolution|Wind Rune Neza|Trash mobs"),
        SkyLine("sky-043|Cleric|Josin Faithbringer|Pauldrons of Piety|Shiny Pauldrons|Isle 5: The Spiroc Lord"),
        SkyLine("sky-044|Cleric|Josin Faithbringer|Pauldrons of Piety|Wind Rune Caza|Trash mobs"),
        SkyLine("sky-052|Cleric|Josin Faithbringer|Theurgist's Star|Djinni Aura|Isle 7: Sister of the Spire"),
        SkyLine("sky-053|Cleric|Josin Faithbringer|Theurgist's Star|Efreeti Mace|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-054|Cleric|Josin Faithbringer|Theurgist's Star|Wind Rune Kala|Trash mobs"),
        SkyLine("sky-045|Cleric|Josin Faithbringer|Truewind Earring|Silver Hoop|Isle 3: Gorgalosk"),
        SkyLine("sky-046|Cleric|Josin Faithbringer|Truewind Earring|Wind Rune Lena|Trash mobs"),
        SkyLine("sky-055|Druid|Strandar Pinemist|Drake-Hide Mask|Worn Leather Mask|Isle 3: Gorgalosk"),
        SkyLine("sky-056|Druid|Strandar Pinemist|Drake-Hide Mask|Wind Rune Meda|Trash mobs"),
        SkyLine("sky-062|Druid|Strandar Pinemist|Espri|Efreeti Scimitar|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-063|Druid|Strandar Pinemist|Espri|Storm Sky Opal|Isle 8: Eye of Veeshan"),
        SkyLine("sky-064|Druid|Strandar Pinemist|Espri|Wind Rune Izah|Trash mobs"),
        SkyLine("sky-065|Druid|Strandar Pinemist|Honeycomb Belt|Divine Honeycomb|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-066|Druid|Strandar Pinemist|Honeycomb Belt|Wind Rune Dena|Trash mobs"),
        SkyLine("sky-057|Druid|Strandar Pinemist|Nature Walker's Mantle|Mantle of Woven Grass|Isle 4: Keeper of Souls"),
        SkyLine("sky-058|Druid|Strandar Pinemist|Nature Walker's Mantle|Wind Rune Kala|Trash mobs"),
        SkyLine("sky-059|Druid|Strandar Pinemist|Shillelagh|Spiroc Battle Staff|Isle 5: The Spiroc Lord"),
        SkyLine("sky-060|Druid|Strandar Pinemist|Shillelagh|Efreeti Statuette|Isle four - griffons and pegasus"),
        SkyLine("sky-061|Druid|Strandar Pinemist|Shillelagh|Wind Rune Azia|Trash mobs"),
        SkyLine("sky-067|Druid|Strandar Pinemist|Spiroc Banisher Focus|Ethereal Ruby|Isle 7: Sister of the Spire"),
        SkyLine("sky-068|Druid|Strandar Pinemist|Spiroc Banisher Focus|Spiroc Elder's Totem|Isle 5: The Spiroc Lord"),
        SkyLine("sky-069|Druid|Strandar Pinemist|Spiroc Banisher Focus|Wind Rune Ena|Trash mobs"),
        SkyLine("sky-070|Enchanter|Enchanter Jolas|Earring of Displacement|Adamantium Earring|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-071|Enchanter|Enchanter Jolas|Earring of Displacement|Wind Rune Caza|Trash mobs"),
        SkyLine("sky-077|Enchanter|Enchanter Jolas|Ivory Mask|Silken Mask|Isle 5: The Spiroc Lord"),
        SkyLine("sky-078|Enchanter|Enchanter Jolas|Ivory Mask|Wind Rune Beza|Trash mobs"),
        SkyLine("sky-072|Enchanter|Enchanter Jolas|Necklace of Whispering Winds|Glowing Necklace|Isle 7: Sister of the Spire"),
        SkyLine("sky-073|Enchanter|Enchanter Jolas|Necklace of Whispering Winds|Wind Rune Fana|Trash mobs"),
        SkyLine("sky-074|Enchanter|Enchanter Jolas|Rod of the Protecting Winds|Efreeti Wind Staff|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-075|Enchanter|Enchanter Jolas|Rod of the Protecting Winds|Large Sky Sapphire|Isle 8: Eye of Veeshan"),
        SkyLine("sky-076|Enchanter|Enchanter Jolas|Rod of the Protecting Winds|Wind Rune Izah|Trash mobs"),
        SkyLine("sky-079|Enchanter|Enchanter Jolas|Sphinx Hair Cord|Finely Woven Cloth Cord|Isle 3: Gorgalosk"),
        SkyLine("sky-080|Enchanter|Enchanter Jolas|Sphinx Hair Cord|Wind Rune Meda|Trash mobs"),
        SkyLine("sky-081|Enchanter|Enchanter Jolas|Wind Walker's Mantle|Light Cloth Mantle|Isle 4: Keeper of Souls"),
        SkyLine("sky-082|Enchanter|Enchanter Jolas|Wind Walker's Mantle|Wind Rune Ozah|Trash mobs"),
        SkyLine("sky-083|Magician|Magus Frinon|Bracelet of Clarification|Feathered Cape|Isle 3: Gorgalosk"),
        SkyLine("sky-084|Magician|Magus Frinon|Bracelet of Clarification|Wind Rune Lena|Trash mobs"),
        SkyLine("sky-089|Magician|Magus Frinon|Drake-Hide Amice|Large Diamond|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-090|Magician|Magus Frinon|Drake-Hide Amice|Wind Rune Dena|Trash mobs"),
        SkyLine("sky-091|Magician|Magus Frinon|Duennan Shielding Ring|Golden Efreeti Ring|Isle 7: Sister of the Spire"),
        SkyLine("sky-092|Magician|Magus Frinon|Duennan Shielding Ring|Wind Rune Ena|Trash mobs"),
        SkyLine("sky-085|Magician|Magus Frinon|Gold White Pendant|Golden Coffer|Isle five - The Spiroc Lord"),
        SkyLine("sky-086|Magician|Magus Frinon|Gold White Pendant|Wind Rune Azia|Trash mobs"),
        SkyLine("sky-087|Magician|Magus Frinon|Mask of Empowerment|Ceramic Mask|Isle 4: Keeper of Souls"),
        SkyLine("sky-088|Magician|Magus Frinon|Mask of Empowerment|Wind Rune Neza|Trash mobs"),
        SkyLine("sky-093|Magician|Magus Frinon|Staff of Elemental Mastery: Air|Crown of Elemental Mastery|Isle 7: 'drake/sphinx/spirit' type mobs"),
        SkyLine("sky-094|Magician|Magus Frinon|Staff of Elemental Mastery: Air|Djinni Stave|Isle 7: Sister of the Spire"),
        SkyLine("sky-095|Magician|Magus Frinon|Staff of Elemental Mastery: Air|Large Opal|Isle 8: Eye of Veeshan"),
        SkyLine("sky-096|Magician|Magus Frinon|Staff of Elemental Mastery: Air|Wind Rune Heda|Trash mobs"),
        SkyLine("sky-097|Magician|Magus Frinon|Staff of the Magister|Efreeti Magi Staff|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-098|Magician|Magus Frinon|Staff of the Magister|Hazy Opal|Isle 8: Eye of Veeshan"),
        SkyLine("sky-099|Magician|Magus Frinon|Staff of the Magister|Wind Rune Jaka|Trash mobs"),
        SkyLine("sky-100|Monk|Holwin|Back Straps of Mastery|Silken Strands|Isle 3: Gorgalosk"),
        SkyLine("sky-101|Monk|Holwin|Back Straps of Mastery|Wind Rune Caza|Trash mobs"),
        SkyLine("sky-106|Monk|Holwin|Golden Sash of Tranquility|Tear of Quellious|Isle 8: Eye of Veeshan"),
        SkyLine("sky-107|Monk|Holwin|Golden Sash of Tranquility|Wind Rune Lena|Trash mobs"),
        SkyLine("sky-102|Monk|Holwin|Sandals of Alacrity|Dove Slippers|Isle 5: The Spiroc Lord"),
        SkyLine("sky-103|Monk|Holwin|Sandals of Alacrity|Wind Rune Jaka|Trash mobs"),
        SkyLine("sky-104|Monk|Holwin|Ton Po's Eye Patch|Cracked Leather Eyepatch|Isle 4: Keeper of Souls"),
        SkyLine("sky-105|Monk|Holwin|Ton Po's Eye Patch|Wind Rune Geza|Trash mobs"),
        SkyLine("sky-108|Monk|Holwin|Ton Po's Shoulder Wraps|Silken Wrap|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-109|Monk|Holwin|Ton Po's Shoulder Wraps|Wind Rune Beza|Trash mobs"),
        SkyLine("sky-110|Monk|Holwin|Wu's Fist of Mastery|Brass Knuckles|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-111|Monk|Holwin|Wu's Fist of Mastery|Nebulous Sapphire|Isle 7: Sister of the Spire"),
        SkyLine("sky-112|Monk|Holwin|Wu's Fist of Mastery|Wind Rune Neza|Trash mobs"),
        SkyLine("sky-113|Necromancer|Drakis Bloodcaster|Band of Wailing Winds|Ring of Veeshan|Isle 7: Sister of the Spire"),
        SkyLine("sky-114|Necromancer|Drakis Bloodcaster|Band of Wailing Winds|Wind Rune Caza|Trash mobs"),
        SkyLine("sky-120|Necromancer|Drakis Bloodcaster|Bloodsoaked Raiment|Fine Cloth Raiment|Isle 5: The Spiroc Lord"),
        SkyLine("sky-121|Necromancer|Drakis Bloodcaster|Bloodsoaked Raiment|Wind Rune Ozah|Trash mobs"),
        SkyLine("sky-122|Necromancer|Drakis Bloodcaster|Bloody Griffon-Hide Wrist Guard|Griffon's Beak|Isle 3: Gorgalosk"),
        SkyLine("sky-123|Necromancer|Drakis Bloodcaster|Bloody Griffon-Hide Wrist Guard|Wind Rune Lena|Trash mobs"),
        SkyLine("sky-124|Necromancer|Drakis Bloodcaster|Cloak of Spiroc Feathers|Black Silk Cape|Isle 4: Keeper of Souls"),
        SkyLine("sky-125|Necromancer|Drakis Bloodcaster|Cloak of Spiroc Feathers|Wind Rune Neza|Trash mobs"),
        SkyLine("sky-115|Necromancer|Drakis Bloodcaster|Gorgon Head Staff|Efreeti Great Staff|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-116|Necromancer|Drakis Bloodcaster|Gorgon Head Staff|Gorgon Head|Isle 3: Gorgalosk"),
        SkyLine("sky-117|Necromancer|Drakis Bloodcaster|Gorgon Head Staff|Wind Rune Fana|Trash mobs"),
        SkyLine("sky-118|Necromancer|Drakis Bloodcaster|Sphinx Heart Amulet|Pulsating Ruby|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-119|Necromancer|Drakis Bloodcaster|Sphinx Heart Amulet|Wind Rune Azia|Trash mobs"),
        SkyLine("sky-126|Paladin|Dason Goldblade|Aldryn, Blade of the Ocean|Bixie Sword Blade|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-127|Paladin|Dason Goldblade|Aldryn, Blade of the Ocean|Wind Rune Ozah|Trash mobs"),
        SkyLine("sky-134|Paladin|Dason Goldblade|Girdle of Faith|Ivory Sky Diamond|Isle 5: The Spiroc Lord"),
        SkyLine("sky-135|Paladin|Dason Goldblade|Girdle of Faith|Wind Rune Lena|Trash mobs"),
        SkyLine("sky-128|Paladin|Dason Goldblade|Thelvorn, Blade of Light|Golden Hilt|Isle two - Protector of Sky"),
        SkyLine("sky-129|Paladin|Dason Goldblade|Thelvorn, Blade of Light|Sphinx Claw|Isle 7: Sister of the Spire"),
        SkyLine("sky-130|Paladin|Dason Goldblade|Thelvorn, Blade of Light|Wind Rune Geza|Trash mobs"),
        SkyLine("sky-131|Paladin|Dason Goldblade|Truvinan|Efreeti Zweihander|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-132|Paladin|Dason Goldblade|Truvinan|Large Sky Diamond|Isle 8: Eye of Veeshan"),
        SkyLine("sky-133|Paladin|Dason Goldblade|Truvinan|Wind Rune Izah|Trash mobs"),
        SkyLine("sky-136|Ranger|Ranger Spirit|Arydryidriyorn|Efreeti Long Sword|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-137|Ranger|Ranger Spirit|Arydryidriyorn|Circlet of Brambles|Isle 7: Sister of the Spire"),
        SkyLine("sky-138|Ranger|Ranger Spirit|Arydryidriyorn|Wind Rune Ena|Trash mobs"),
        SkyLine("sky-144|Ranger|Ranger Spirit|Dark Cloak of the Sky|Fine Velvet Cloak|Isle 4: Keeper of Souls"),
        SkyLine("sky-145|Ranger|Ranger Spirit|Dark Cloak of the Sky|Wind Rune Neza|Trash mobs"),
        SkyLine("sky-146|Ranger|Ranger Spirit|Earthshaker's Mantle|Spiroc Earth Totem|Isle 5: The Spiroc Lord"),
        SkyLine("sky-147|Ranger|Ranger Spirit|Earthshaker's Mantle|Wind Rune Kala|Trash mobs"),
        SkyLine("sky-148|Ranger|Ranger Spirit|Griffon Talon Necklace|Griffon Talon|Isle 3: Gorgalosk"),
        SkyLine("sky-149|Ranger|Ranger Spirit|Griffon Talon Necklace|Wind Rune Meda|Trash mobs"),
        SkyLine("sky-139|Ranger|Ranger Spirit|Thunderforged Earring|White Gold Earring|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-140|Ranger|Ranger Spirit|Thunderforged Earring|Wind Rune Azia|Trash mobs"),
        SkyLine("sky-141|Ranger|Ranger Spirit|Windstriker|Efreeti War Bow|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-142|Ranger|Ranger Spirit|Windstriker|Shimmering Pearl|Isle 8: Eye of Veeshan"),
        SkyLine("sky-143|Ranger|Ranger Spirit|Windstriker|Wind Rune Heda|Trash mobs"),
        SkyLine("sky-150|Rogue|Thalik Silenthand|Crystal Mask|Jester's Mask|Isle 4: Keeper of Souls"),
        SkyLine("sky-151|Rogue|Thalik Silenthand|Crystal Mask|Wind Rune Dena|Trash mobs"),
        SkyLine("sky-157|Rogue|Thalik Silenthand|Griffon Wing Spaulders|Spiroc Sky Totem|Isle 5: The Spiroc Lord"),
        SkyLine("sky-158|Rogue|Thalik Silenthand|Griffon Wing Spaulders|Wind Rune Ena|Trash mobs"),
        SkyLine("sky-159|Rogue|Thalik Silenthand|Renard's Belt of Quickness|Sphinxian Circlet|Isle 7: Sister of the Spire"),
        SkyLine("sky-160|Rogue|Thalik Silenthand|Renard's Belt of Quickness|Wind Rune Izah|Trash mobs"),
        SkyLine("sky-152|Rogue|Thalik Silenthand|Scintillating Bracer of Protection|Fine Wool Cloak|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-153|Rogue|Thalik Silenthand|Scintillating Bracer of Protection|Wind Rune Geza|Trash mobs"),
        SkyLine("sky-154|Rogue|Thalik Silenthand|Thornstinger|Bixie Stinger|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-155|Rogue|Thalik Silenthand|Thornstinger|Bloodsky Sapphire|Isle 8: Eye of Veeshan"),
        SkyLine("sky-156|Rogue|Thalik Silenthand|Thornstinger|Wind Rune Jaka|Trash mobs"),
        SkyLine("sky-161|Rogue|Thalik Silenthand|Wispy Choker of Vigor|Inlaid Choker|Isle 3: Gorgalosk"),
        SkyLine("sky-162|Rogue|Thalik Silenthand|Wispy Choker of Vigor|Wind Rune Ozah|Trash mobs"),
        SkyLine("sky-178|Shadow Knight|Sarkis Ebonblade|Amulet of the Sphinx Eye|Finely Crafted Amulet|Isle 3: Gorgalosk"),
        SkyLine("sky-179|Shadow Knight|Sarkis Ebonblade|Amulet of the Sphinx Eye|Wind Rune Ozah|Trash mobs"),
        SkyLine("sky-184|Shadow Knight|Sarkis Ebonblade|Blood Sky Face Plate|Rusted Pauldrons|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-185|Shadow Knight|Sarkis Ebonblade|Blood Sky Face Plate|Wind Rune Fana|Trash mobs"),
        SkyLine("sky-180|Shadow Knight|Sarkis Ebonblade|Crimson Ring of the Djinni|Silvery Ring|Isle 4: Keeper of Souls"),
        SkyLine("sky-181|Shadow Knight|Sarkis Ebonblade|Crimson Ring of the Djinni|Wind Rune Beza|Trash mobs"),
        SkyLine("sky-186|Shadow Knight|Sarkis Ebonblade|Khyldorn the Blood Drinker|Blood Sky Ruby|Isle 8: Eye of Veeshan"),
        SkyLine("sky-187|Shadow Knight|Sarkis Ebonblade|Khyldorn the Blood Drinker|Efreeti War Axe|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-188|Shadow Knight|Sarkis Ebonblade|Khyldorn the Blood Drinker|Wind Rune Kala|Trash mobs"),
        SkyLine("sky-189|Shadow Knight|Sarkis Ebonblade|Obtenebrate Mithril Guard|Efreeti War Shield|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-190|Shadow Knight|Sarkis Ebonblade|Obtenebrate Mithril Guard|Wind Rune Heda|Trash mobs"),
        SkyLine("sky-191|Shadow Knight|Sarkis Ebonblade|Pearlescent Pauldrons|Fae Pauldrons|Isle 8: Eye of Veeshan"),
        SkyLine("sky-192|Shadow Knight|Sarkis Ebonblade|Pearlescent Pauldrons|Sphinxian Ring|Isle 7: Sister of the Spire"),
        SkyLine("sky-193|Shadow Knight|Sarkis Ebonblade|Pearlescent Pauldrons|Wind Rune Izah|Trash mobs"),
        SkyLine("sky-182|Shadow Knight|Sarkis Ebonblade|Pegasus-Hide Belt|Finely Woven Cloth Belt|Isle 5: The Spiroc Lord"),
        SkyLine("sky-183|Shadow Knight|Sarkis Ebonblade|Pegasus-Hide Belt|Wind Rune Dena|Trash mobs"),
        SkyLine("sky-163|Shaman|Medicine Man Veetra|Amulet of the Fang|Leather Cord|Isle 3: Gorgalosk"),
        SkyLine("sky-164|Shaman|Medicine Man Veetra|Amulet of the Fang|Wind Rune Meda|Trash mobs"),
        SkyLine("sky-165|Shaman|Medicine Man Veetra|Bracelet of the Spirits|Ceremonial Belt|Isle 5: The Spiroc Lord"),
        SkyLine("sky-166|Shaman|Medicine Man Veetra|Bracelet of the Spirits|Wind Rune Kala|Trash mobs"),
        SkyLine("sky-167|Shaman|Medicine Man Veetra|Fairy-Hide Mantle|Light Damask Mantle|Isle 5: The Spiroc Lord"),
        SkyLine("sky-168|Shaman|Medicine Man Veetra|Fairy-Hide Mantle|Wind Rune Beza|Trash mobs"),
        SkyLine("sky-169|Shaman|Medicine Man Veetra|Garduk|Efreeti War Maul|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-170|Shaman|Medicine Man Veetra|Garduk|Symbol of Veeshan|Isle 8: Eye of Veeshan"),
        SkyLine("sky-171|Shaman|Medicine Man Veetra|Garduk|Wind Rune Geza|Trash mobs"),
        SkyLine("sky-172|Shaman|Medicine Man Veetra|Vermilion Sky Ring|Bixie Essence|Isle six - bees"),
        SkyLine("sky-173|Shaman|Medicine Man Veetra|Vermilion Sky Ring|Spiritualist`s Ring|Isle 7: Sister of the Spire"),
        SkyLine("sky-174|Shaman|Medicine Man Veetra|Vermilion Sky Ring|Wind Rune Heda|Trash mobs"),
        SkyLine("sky-175|Shaman|Medicine Man Veetra|Warhammer of the Wind|Corrosive Venom|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-176|Shaman|Medicine Man Veetra|Warhammer of the Wind|Efreeti War Club|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-177|Shaman|Medicine Man Veetra|Warhammer of the Wind|Wind Rune Ena|Trash mobs"),
        SkyLine("sky-194|Warrior|Torgon Blademaster|Azure Ruby Ring|Azure Ring|Isle 3: Gorgalosk"),
        SkyLine("sky-195|Warrior|Torgon Blademaster|Azure Ruby Ring|Wind Rune Neza|Trash mobs"),
        SkyLine("sky-200|Warrior|Torgon Blademaster|Belt of the Four Winds|Efreeti Belt|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-201|Warrior|Torgon Blademaster|Belt of the Four Winds|Wind Tablet|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-202|Warrior|Torgon Blademaster|Belt of the Four Winds|Wind Rune Fana|Trash mobs"),
        SkyLine("sky-203|Warrior|Torgon Blademaster|Dagas|Djinni War Blade|Isle 7: Sister of the Spire"),
        SkyLine("sky-204|Warrior|Torgon Blademaster|Dagas|Gem of Invigoration|Isle two - Protector of Sky"),
        SkyLine("sky-205|Warrior|Torgon Blademaster|Dagas|Wind Rune Jaka|Trash mobs"),
        SkyLine("sky-206|Warrior|Torgon Blademaster|Fangol|Efreeti Battle Axe|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-207|Warrior|Torgon Blademaster|Fangol|Ethereal Emerald|Isle 8: Eye of Veeshan"),
        SkyLine("sky-208|Warrior|Torgon Blademaster|Fangol|Wind Rune Dena|Trash mobs"),
        SkyLine("sky-196|Warrior|Torgon Blademaster|Pauldrons of the Blue Sky|Spiroc Air Totem|Isle 5: The Spiroc Lord"),
        SkyLine("sky-197|Warrior|Torgon Blademaster|Pauldrons of the Blue Sky|Wind Rune Beza|Trash mobs"),
        SkyLine("sky-198|Warrior|Torgon Blademaster|Runed Wind Amulet|Stone Amulet|Isle 4: Keeper of Souls"),
        SkyLine("sky-199|Warrior|Torgon Blademaster|Runed Wind Amulet|Wind Rune Azia|Trash mobs"),
        SkyLine("sky-209|Wizard|Wizard Schrock|Al`Kabor's Cap of Binding|Woven Skull Cap|Isle 4: Keeper of Souls"),
        SkyLine("sky-210|Wizard|Wizard Schrock|Al`Kabor's Cap of Binding|Wind Rune Fana|Trash mobs"),
        SkyLine("sky-215|Wizard|Wizard Schrock|Amulet of the Void|Amethyst Amulet|Isle 7: Sister of the Spire"),
        SkyLine("sky-216|Wizard|Wizard Schrock|Amulet of the Void|Wind Rune Jaka|Trash mobs"),
        SkyLine("sky-211|Wizard|Wizard Schrock|Augmentor's Mask|Grey Damask Cloak|Isle 3: Gorgalosk"),
        SkyLine("sky-212|Wizard|Wizard Schrock|Augmentor's Mask|Wind Rune Dena|Trash mobs"),
        SkyLine("sky-217|Wizard|Wizard Schrock|Nargon's Staff|Efreeti War Staff|Isle eight: the Hand of Veeshan; Isle four: Overseer of Air; Isle 1.5: Noble Dojorn"),
        SkyLine("sky-218|Wizard|Wizard Schrock|Nargon's Staff|Large Sky Lapis|Isle 8: Eye of Veeshan"),
        SkyLine("sky-219|Wizard|Wizard Schrock|Nargon's Staff|Wind Rune Caza|Trash mobs"),
        SkyLine("sky-213|Wizard|Wizard Schrock|Raiment of Thunder|High Quality Raiment|Isle 5: The Spiroc Lord"),
        SkyLine("sky-214|Wizard|Wizard Schrock|Raiment of Thunder|Wind Rune Geza|Trash mobs"),
        SkyLine("sky-220|Wizard|Wizard Schrock|Solidate Mithril Ring|Box of Winds|Isle 6: Bazzt Zzzt"),
        SkyLine("sky-221|Wizard|Wizard Schrock|Solidate Mithril Ring|Efreeti Statuette|Isle four - griffons and pegasus"),
        SkyLine("sky-222|Wizard|Wizard Schrock|Solidate Mithril Ring|Wind Rune Izah|Trash mobs"),
    ];

    private static SkyQuestChecklistItem SkyLine(string line)
    {
        var parts = line.Split('|');
        return new SkyQuestChecklistItem
        {
            Id = parts[0],
            ClassName = parts[1],
            Npc = parts[2],
            Reward = parts[3],
            QuestItem = parts[4],
            Source = parts[5],
        };
    }
}
